<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-07-15 10:53

$extensionPath = t3lib_extMgm::extPath('bib');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_bib_citeid_generator' => $extensionPath . 'pi1/class.tx_bib_citeid_generator.php',
	'tx_bib_citeid_generator_ext' => $extensionClassesPath . 'Utility/class.tx_bib_citeid_generator_ext.php',
	'tx_bib_db_utility' => $extensionClassesPath . 'Utility/class.tx_bib_db_utility.php',
	'tx_bib_editor_view' => $extensionPath . 'pi1/class.tx_bib_editor_view.php',
	'tx_bib_exporter' => $extensionClassesPath . 'Utility/Exporter/class.tx_bib_exporter.php',
	'tx_bib_exporter_bibtex' => $extensionClassesPath . 'Utility/Exporter/class.tx_bib_exporter_bibtex.php',
	'tx_bib_exporter_xml' => $extensionClassesPath . 'Utility/Exporter/class.tx_bib_exporter_xml.php',
	'tx_bib_importer' => $extensionClassesPath . 'Utility/Importer/class.tx_bib_importer.php',
	'tx_bib_importer_bibtex' => $extensionClassesPath . 'Utility/Importer/class.tx_bib_importer_bibtex.php',
	'tx_bib_importer_xml' => $extensionClassesPath . 'Utility/Importer/class.tx_bib_importer_xml.php',
	'tx_bib_labels' => $extensionClassesPath . 'Utility/class.tx_bib_labels.php',
	'tx_bib_navi' => $extensionPath . 'pi1/class.tx_bib_navi.php',
	'tx_bib_navi_author' => $extensionPath . 'pi1/class.tx_bib_navi_author.php',
	'tx_bib_navi_page' => $extensionPath . 'pi1/class.tx_bib_navi_page.php',
	'tx_bib_navi_pref' => $extensionPath . 'pi1/class.tx_bib_navi_pref.php',
	'tx_bib_navi_search' => $extensionPath . 'pi1/class.tx_bib_navi_search.php',
	'tx_bib_navi_stat' => $extensionPath . 'pi1/class.tx_bib_navi_stat.php',
	'tx_bib_navi_year' => $extensionPath . 'pi1/class.tx_bib_navi_year.php',
	'tx_bib_parser_exception' => $extensionClassesPath . 'Utility/Importer/class.tx_bib_importer_bibtex.php',
	'tx_bib_pi1' => $extensionPath . 'pi1/class.tx_bib_pi1.php',
	'tx_bib_reference_writer' => $extensionClassesPath . 'Utility/class.tx_bib_reference_writer.php',
	'tx_bib_single_view' => $extensionPath . 'pi1/class.tx_bib_single_view.php',
	'tx_bib_translator_exception' => $extensionClassesPath . 'Utility/Importer/class.tx_bib_importer_bibtex.php',
	'tx_bib_utility_pregexptanslator' => $extensionClassesPath . 'Utility/PRegExpTanslator.php',
	'tx_bib_utility_referencereader' => $extensionClassesPath . 'Utility/ReferenceReader.php',
	'tx_bib_utility_utility' => $extensionClassesPath . 'Utility/Utility.php',
);
?>