<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-09-02 17:30

$extensionPath = t3lib_extMgm::extPath('bib');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_bib_controller_indexcontroller' => $extensionClassesPath . 'Controller/IndexController.php',
	'tx_bib_domain_model_author' => $extensionClassesPath . 'Domain/Model/Author.php',
	'tx_bib_domain_model_references' => $extensionClassesPath . 'Domain/Model/References.php',
	'tx_bib_editor_view' => $extensionPath . 'pi1/class.tx_bib_editor_view.php',
	'tx_bib_navi' => $extensionPath . 'pi1/class.tx_bib_navi.php',
	'tx_bib_navi_author' => $extensionPath . 'pi1/class.tx_bib_navi_author.php',
	'tx_bib_navi_page' => $extensionPath . 'pi1/class.tx_bib_navi_page.php',
	'tx_bib_navi_pref' => $extensionPath . 'pi1/class.tx_bib_navi_pref.php',
	'tx_bib_navi_search' => $extensionPath . 'pi1/class.tx_bib_navi_search.php',
	'tx_bib_navi_stat' => $extensionPath . 'pi1/class.tx_bib_navi_stat.php',
	'tx_bib_navi_year' => $extensionPath . 'pi1/class.tx_bib_navi_year.php',
	'tx_bib_pi1' => $extensionPath . 'pi1/class.tx_bib_pi1.php',
	'tx_bib_single_view' => $extensionPath . 'pi1/class.tx_bib_single_view.php',
);
?>